# -*- coding: utf-8 -*-
"""lymphoma llm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xTmIO2iZRbxPBUCX_RDof_BJgXwbvAYk
"""

!pip install flask openai langchain faiss-cpu requests beautifulsoup4 pinecone-client

+